baseURL = "http://localhost:1313/"
repoName = "GitRepoName"
environment = "prod"
languageCode = "en-us"

[taxonomies]
  tag = "tags"
  IndustryType = "IndustryType"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true



[params]
  CompanyName = "My Hugo Site"


[outputs]
  section = ["HTML", "JSON"]
